---
# tasks file for slacko

- name: Clone repo git
  git:
    repo: https://github.com/LeonardoDG2084/iaac_slacko-api
    dest: /opt
    separate_git_dir: /opt/ansible-examples.git

- name: Install Banco mongoDB
  apt:
    name: mongodb
    state: present
    update_cache: yes
  notify:
    - carregar mongodb      

- name: Instalando Requimento Python
  pip: 
    requirements: /opt/requeriments.txt

- name: Criacao do diretorio slacko-api
  file:
    path: "{{ path_api }}"
    state: directory

- name: Copiar arquivos para diretorio
  copy: 
    src: "{{ item }}"
    dest: "{{ path_api }}"
    mode: '0755'
    remote_src: yes
  with_items:
    - /opt/main.py

- name: 'copia e configura arquivo para diretorio'
  template: 
    src: templates/slacko-api.sh
    dest: "{{ path_api }}"
    mode: '0755'

- name: Iniciar Servico
  template: 
    src: templates/slacko-api.service
    dest: /etc/systemd/system/
    owner: root
    group: root
  notify:
    - Start slacko-api.service
